# Generated by Django 5.0.7 on 2026-07-22 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('repair', 'Repair'), ('service', 'Service'), ('tyre_replacement', 'Tyre replacement'), ('brake_service', 'Brake service'), ('inspection', 'Inspection'), ('insurance_renewal', 'Insurance renewal'), ('license_renewal', 'License renewal')], max_length=30)),
                ('workshop', models.CharField(blank=True, max_length=150)),
                ('mechanic', models.CharField(blank=True, max_length=150)),
                ('parts_used', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('downtime_days', models.PositiveIntegerField(default=0)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_number', models.CharField(max_length=30, unique=True)),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('vin', models.CharField(max_length=60, unique=True, verbose_name='VIN / chassis number')),
                ('trailer_type', models.CharField(choices=[('flatbed', 'Flatbed'), ('low_loader', 'Low Loader'), ('fuel_tanker', 'Fuel Tanker'), ('container', 'Container Trailer'), ('side_tipper', 'Side Tipper'), ('box', 'Box Trailer'), ('curtain', 'Curtain Trailer'), ('refrigerated', 'Refrigerated Trailer'), ('skeletal', 'Skeletal Trailer'), ('extendable', 'Extendable Trailer'), ('livestock', 'Livestock Trailer'), ('other', 'Other')], max_length=30)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('rented', 'Rented'), ('under_maintenance', 'Under Maintenance'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='available', max_length=30)),
                ('yard_location', models.CharField(blank=True, max_length=150)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('qr_code_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trailer_number'],
            },
        ),
        migrations.CreateModel(
            name='TrailerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('insurance', 'Insurance certificate'), ('logbook', 'Logbook'), ('inspection_report', 'Inspection report'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='trailers/documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrailerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trailers/images/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('before_rental', 'Before rental'), ('after_return', 'After return')], max_length=20)),
                ('description', models.TextField()),
                ('damage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_claim_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='rentals.rental')),
            ],
        ),
    ]
