# Generated by Django 5.0.7 on 2026-07-22 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('trailers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trailer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailers', to='core.branch'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='trailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='trailers.trailer'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='trailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='trailers.trailer'),
        ),
        migrations.AddField(
            model_name='trailerdocument',
            name='trailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trailers.trailer'),
        ),
        migrations.AddField(
            model_name='trailerimage',
            name='trailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trailers.trailer'),
        ),
    ]
