# Generated by Django 5.0.7 on 2026-07-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='insurance_expiry',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='license_expiry',
        ),
    ]
