# Generated by Django 5.0.7 on 2026-07-22 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pickup', 'Pickup'), ('return', 'Return')], max_length=20)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('rental_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('long_term', 'Long Term')], default='monthly', max_length=20)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=200)),
                ('dropoff_location', models.CharField(blank=True, max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fuel_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_return_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damage_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reserved', 'Reserved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('agreement_signed', models.BooleanField(default=False)),
                ('agreement_file', models.FileField(blank=True, null=True, upload_to='rentals/agreements/')),
                ('signature_file', models.FileField(blank=True, null=True, upload_to='rentals/signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='clients.client')),
            ],
            options={
                'ordering': ['-pickup_date'],
            },
        ),
    ]
