# Generated by Codex on 2026-07-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_initial"),
    ]

    operations = [
        migrations.AddField(model_name="rental", name="cancelled_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="rental", name="cancelled_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="rental", name="cancellation_reason", field=models.TextField(blank=True)),
        migrations.AddField(model_name="rental", name="confirmed_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="rental", name="confirmed_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="rental", name="deposit_forfeited", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="rental", name="deposit_notes", field=models.TextField(blank=True)),
        migrations.AddField(model_name="rental", name="deposit_received", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="rental", name="deposit_refunded", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AlterField(model_name="rental", name="status", field=models.CharField(choices=[("draft", "Draft"), ("reserved", "Reserved"), ("active", "Active"), ("returned", "Returned"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="draft", max_length=20)),
    ]
