# Generated by Django 5.0.7 on 2026-07-22 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='company', max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Name / company name')),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('pin', models.CharField(blank=True, max_length=20, verbose_name='Postal / location PIN')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('kra_pin', models.CharField(blank=True, max_length=30)),
                ('national_id', models.CharField(blank=True, max_length=30)),
                ('passport', models.CharField(blank=True, max_length=30)),
                ('business_registration', models.CharField(blank=True, max_length=60)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('preferred_payment_terms', models.CharField(choices=[('cash', 'Cash'), ('net_7', 'Net 7'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_60', 'Net 60')], default='net_30', max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('blacklisted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='clients/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
