# Generated by Django 5.0.7 on 2026-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_allow_blank_client_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('KES', 'Kenyan Shillings')], default='USD', max_length=3),
        ),
    ]
