# Generated by Django 5.0.7 on 2026-07-28 05:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_currency'),
        ('quotations', '0006_rename_quotation_response_token_idx_quotations__token_51d8e8_idx_and_more'),
        ('rentals', '0003_rental_lifecycle_operations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocumentSigningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='clients/signing/contracts/')),
                ('inspection_pdf', models.FileField(blank=True, null=True, upload_to='clients/signing/inspections/')),
                ('signed_contract_file', models.FileField(blank=True, null=True, upload_to='clients/signing/signed_contracts/')),
                ('signed_inspection_file', models.FileField(blank=True, null=True, upload_to='clients/signing/signed_inspections/')),
                ('contract_status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('uploaded', 'Uploaded'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('inspection_status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('uploaded', 'Uploaded'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_signing_requests', to='clients.client')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signing_requests', to='quotations.quotation')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signing_requests', to='rentals.rental')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSigningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('declined', 'Declined')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.clientdocumentsigningrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
