# Generated by Django 5.0.7 on 2026-07-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientdocumentsigningrequest_documentsigningevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='outstanding_balance',
        ),
    ]
