# Generated by Django 5.0.7 on 2026-07-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_add_response_tokens'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quotationresponsetoken',
            new_name='quotations__token_51d8e8_idx',
            old_name='quotation_response_token_idx',
        ),
        migrations.RenameIndex(
            model_name='quotationresponsetoken',
            new_name='quotations__quotati_8a7d06_idx',
            old_name='quotation_response_quotation_action_idx',
        ),
    ]
